---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: directus-uploads
  namespace: mineral-museum
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
